### ISSUE TITLE
cant get it installed please help me out

### ISSUE THREAD

**Issue by Dannybe** [dragon3/rhythmbox-twitter-plugin#11]
right i've follow what is says

((( \* Install Python libraries.
$ sudo apt-get install python-httplib2 python-gconf python-gobject python-gtk2 python-gnome2 python-glade2 python-twitter
- Install this plugin
  $ cd /tmp
  $ wget http://github.com/dragon3/rhythmbox-...tarball/master
  $ tar zxfv dragon3-rhythmbox-twitter-plugin-_.tar.gz
  $ cd dragon3-rhythmbox-twitter-plugin-_
  $ make install )))

but as soon as i get to "tar zxfv dragon3-rhythmbox-twitter-plugin-*.tar.gz" 

i get can not open no such file
error is not recoverable
child returned status 2
exiting with failure status due to previous errors,

**Comment by dragon3** [comment]
Hi, Dannybe.
Please check this site. 
http://dragon3.github.com/rhythmbox-twitter-plugin/

**Comment by Dannybe** [comment]
thank you very much, i did that a few times and above was the result i got, but for some reason it worked this time, thank you :))
