### ISSUE TITLE
Configure window does not appear.

### ISSUE THREAD

**Issue by Tokynet** [dragon3/rhythmbox-twitter-plugin#2]
When I enable the plugin and click on the configure button this is what happens:
//CODE//
Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/twitter-plug/twitter-plugin.py", line 112, in create_configure_dialog
    dialog = TwitterConfigureDialog (glade_file).get_dialog()
  File "/usr/lib/rhythmbox/plugins/twitter-plug/twitter-plugin.py", line 122, in **init**
    gladexml = gtk.glade.XML(glade_file)
TypeError: GladeXML.**init**() argument 1 must be string, not None

(rhythmbox:9449): Rhythmbox-CRITICAL **: rb_plugins_engine_configure_plugin: assertion `conf_dlg != NULL' failed

(rhythmbox:9449): Rhythmbox-WARNING **: Unable to stop mDNS browsing: mDNS service is not running
//CODE//

This is on Arch-Linux

**Comment by dragon3** [comment]
Hi, 
I think, your install directory is not correct.

Your install directory is

> /usr/lib/rhythmbox/plugins/twitter-plug/

but correct directory is

> /usr/lib/rhythmbox/plugins/twitter-plugin/

Please check.

**Comment by dragon3** [comment]
Hi,  Tokynet.
You also install here.

> ~/.gnome2/rhythmbox/plugins/twitter-plugin/

**Comment by dragon3** [comment]
Hi, Tokynet.
Is your problem already resolved?

**Comment by Tokynet** [comment]
Yes I had changed the install directory, I thought it would be configurable/changeable.

I did changed it back to the suggested path, Thanks.
Thanks for your prompt reply!

**Comment by dragon3** [comment]
Thank you, Tokynet.
