### ISSUE TITLE
Support Spanish

### ISSUE THREAD

**Issue by dragon3** [dragon3/rhythmbox-twitter-plugin#8]
Francisco Ramírez send me Spanish version. (Thanks)
After finish i18n (#7), I would like to do this.

**Comment by leomeloxp** [comment]
I don't know how requested it is, but I can do Portuguese version if you teach me how to.

**Comment by dragon3** [comment]
Thank you, Leo-san !
After I finish i18n (#7), please help me to create Portuguese version. (#9)
